### PR TITLE
Optimize PNGs (lossless compression)

### PR DESCRIPTION
**Pull request by abennouna**

### CODE REVIEW

**Comment by ouadie-lahdioui** [comment]
Top, merci @abennouna 

T'as utilisé quel outil pour faire cette optimisation ?

**Comment by abennouna** [comment]
@ouadie-lahdioui since those are static files, I did it manually through two Mac apps https://pngmini.com/ + https://imageoptim.com/mac.

However, the first one, as you can read on their website, is based on https://pngquant.org/

Last but not least: I dubbed the compression _lossless_ in the PR title; in fact, it's **lossy** compression.

**Comment by abennouna** [comment]
By the way: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fngmorocco.org

**Comment by ouadie-lahdioui** [comment]
Intéressent

**Pull request merged**
